Horario/Horario.WebUI/Controllers/ProfesorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Horario.Domain.Abstract;
using Horario.Domain.Entities;
using Horario.Domain.Concrete;
using System.Globalization;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data;

namespace Horario.WebUI.Controllers
{
    public class ProfesorController : Controller
    {
        // GET: Profesor
        /*public ActionResult Index()
        {
            return View();
        }*/

        private HorarioEntities context = new HorarioEntities();

        public IProfesorRepository repository;


        public ProfesorController(IProfesorRepository profesorRepository)
        {
            repository = profesorRepository;
        }

        public ViewResult Horario(String Nomina, string DiaTexto)
        {

            //--'01/08/2008 20:00' mes/dia/año hora
            //int Semana = int.Parse(SemanaTexto);
            CultureInfo provider = CultureInfo.InvariantCulture;
            DateTime Dia = DateTime.ParseExact(DiaTexto, "yyyy-MM-dd", provider);
            DateTime DiaMenos7 = Dia.AddDays(-7.0);
            DateTime DiaMas7 = Dia.AddDays(7.0);
            /*switch (Semana)
            {
                case -1:
                    Dia = Dia.AddDays(-7.0);
                    break;
                case 1:
                    Dia = Dia.AddDays(7.0);
                    break;
            }*/
            //var CosaE = Tuple.Create(21.5, 23.0);

            HorarioViewModel Cosa = new HorarioViewModel(context.PROFESOR.Find(Nomina), Dia, DiaMas7, DiaMenos7);

            //return View(context.regresarHorario(Nomina, diadia));
            return View(Cosa);
        }

        [HttpPost]
        public RedirectResult crearCita(string NominaProfeC, string NombrePersona, string Asunto, string Fecha, string HoraInicio, string HoraFin)
        {

            try
            {
                using (SqlConnection conn = new SqlConnection("data source=JOSUE;initial catalog=ProyectoFinalBD;integrated security=True;multipleactiveresultsets=True;application name=EntityFramework;"))
                {
                    SqlCommand command = new SqlCommand("esCitaValida", conn);
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.Add("@DiaCTexto", SqlDbType.NVarChar).Value = Fecha;
                    command.Parameters.Add("@HoraFCTexto", SqlDbType.NVarChar).Value = HoraFin;
                    command.Parameters.Add("@HoraICTexto", SqlDbType.NVarChar).Value = HoraInicio;
                    command.Parameters.Add("@NominaP", SqlDbType.NVarChar).Value = NominaProfeC;

                    command.Parameters.Add("@CitaCorrecta", SqlDbType.Bit).Direction = ParameterDirection.ReturnValue;
                    conn.Open();

                    command.ExecuteNonQuery();

                    int esCitaValida = int.Parse(command.Parameters["@CitaCorrecta"].Value.ToString());

                    if (esCitaValida==1)
                    {
                        CITA Cita = new CITA();
                        CultureInfo provider = CultureInfo.InvariantCulture;

                        Cita.Asunto = Asunto;
                        Cita.Fecha = DateTime.ParseExact(Fecha, "yyyy-MM-dd", provider);
                        Cita.HoraInicio = TimeSpan.ParseExact(HoraInicio, "g", provider);
                        Cita.HoraFin = TimeSpan.ParseExact(HoraFin, "g", provider);
                        Cita.NombrePersona = NombrePersona;
                        Cita.NominaP = NominaProfeC;

                        context.CITA.Add(Cita);
                        context.SaveChanges();

                        //TempData["message"] = "Tu cita se creó correctamente.";
                        //return RedirectToAction("List");
                        return Redirect("https://www.facebook.com/");
                        //return RedirectToAction("List", "Profesor", ViewBag);
                        //return View(repository);
                        //return View("List", repository);

                    }
                    else
                    {
                        //TempData["message"] = "Lo sentimos, no se pudo crear tu cita. Asegurate de haber escrito bien los datos, de no haber puesto una fecha u hora que ya pasó, de que la fecha no sea Sábado o Domingo o que no intefiera con otra cita.";
                        //return RedirectToAction("List");
                        return Redirect("https://www.google.com.mx");
                        //return RedirectToAction("List", "Profesor", null);
                        //return RedirectToAction("List", "Profesor", ViewBag);
                        //return View("List", repository);
                    }

                }
            }
            catch (Exception error)
            {
                //TempData["message"] = string.Format("Lo sentimos, ha habido un error al crear la cita: "+error.Message);
                //return RedirectToAction("List");
                return Redirect("https://www.myspace.com");
                //return RedirectToAction("List", "Profesor", null);
                //return RedirectToAction("List", "Profesor", ViewBag);
                //return View("List", repository);
            }
        }

        public ViewResult List()
        {
            //ViewBag.message = "";
            return View(repository);
        }
    }
}

Horario/Horario.WebUI/Views/Profesor/Horario.cshtml
@model  Horario.Domain.Concrete.HorarioViewModel

@{
    ViewBag.Title = "Horario";
}

<h1>Horario de @Model.Profe.Nombre @Model.Profe.Apellido</h1>
<br />
@Html.ActionLink("Regresar a Profesores", "List")
<br />
@Html.ActionLink("Semana anterior", "Horario", new { Nomina = @Model.Profe.Nomina, DiaTexto = Model.regresarDiaMenos7() })
<br />
@Html.ActionLink("Semana siguiente", "Horario", new { Nomina = @Model.Profe.Nomina, DiaTexto = Model.regresarDiaMas7() })

<div class="row">
    <div class="col-lg-6">
        <table class="table">
            <tr>
                @foreach (var Encabezado in Model.regresarEncabezadosSemana())
                {
                    <th>@Encabezado.Encabezados</th>
                }
            </tr>
            @foreach (var renglon in Model.regresarHorario())
            {
                <tr>
                    <th>@renglon.Mes</th>
                    <th>@renglon.Lunes</th>
                    <th>@renglon.Martes</th>
                    <th>@renglon.Miercoles</th>
                    <th>@renglon.Jueves</th>
                    <th>@renglon.Viernes</th>
                </tr>
            }
        </table>
    </div>
    <div class="col-lg-6">
        <center><button onclick="Mostrar()" style="position: fixed;" id="Mas" class="btn">Generar cita con @Model.Profe.Nombre</button></center>
       
        <div id="Completo" style="position: fixed; display:none;">
            @using (Html.BeginForm("crearCita", "Profesor", new { NominaProfeC = Model.Profe.Nomina }, FormMethod.Post, null))
            {
                <center>
                    <center><h4>Nueva cita con @Model.Profe.Nombre</h4></center>
                    <div class="panel-body">
                        <p>Tu nombre:@Html.TextBox("NombrePersona", null, new { @class = "form-control" })</p>
                        <p>Asunto:@Html.TextBox("Asunto", null, new { @class = "form-control" })</p>
                        <p>Día:@Html.TextBox("Fecha", null, new { @class = "form-control", @pattern= "(2016)[-]((1|0)[0-2]|[0][0-9])[-]((1|0|2)[0-9]|[3][0-1])" })</p>
                        <p>De:@Html.TextBox("HoraInicio", null, new { @class = "form-control", @pattern= "[0-2][0-9][:](0|3)[0][:][0][0]" })</p>
                        <p>A:@Html.TextBox("HoraFin", null, new { @class = "form-control", @pattern = "[0-2][0-9][:](0|3)[0][:][0][0]" })</p>
</div>
                    <div class="panel-footer">
                        <input type="submit" value="Crear" />
                    </div>
                </center>
            }
        </div>
        
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
<script type="text/javascript">
            function Mostrar(){
                $("#Mas").toggle(function(){
                    $("#Completo").show();
                    //add property fixed
                    $(this).hide();
                });
            }
</script>

Horario/Horario.WebUI/Views/Profesor/Inicio.cshtml
@model Horario.Domain.Concrete.EFProfesorRepository

@{
    ViewBag.Title = "Inicio";
}

@foreach (var prof in Model.Inicio)
{
    <div>
        <h3>@prof.Nombre @prof.Apellido</h3>
        
        <img src="@prof.Foto" />
        @{
            if (@prof.Ocupado == "No")
            {
                <button onclick="Unafuncion('@prof.Nomina')"> Timbrar</button>
            }
         }
    </div>
}

Horario/Horario.WebUI/Views/Profesor/List.cshtml
@model  Horario.Domain.Concrete.EFProfesorRepository

@{
    ViewBag.Title = "Profesores disponibles";
}

@foreach (var prof in Model.Profesores)
{
    <div>
        <h3>@prof.Nombre @prof.Apellido</h3>
        @prof.Nomina
        <br />
        @prof.Area
        <br />
        @Html.ActionLink("Ver horario", "Horario", new { Nomina = @prof.Nomina, DiaTexto = DateTime.Now.ToString("yyyy-MM-dd")})
    </div>
}

@if (TempData["message"] != null)
{
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
    <script type="text/javascript">
        alert(@TempData["message"]);
    </script>
}

Horario/Horario.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>